fs = require 'fs'
{ exec } = require 'child_process'

# execute command and print its result
ep = (command) ->
  exec command, (err, stdout, stderr) ->
    throw err if err
    console.log stdout + stderr

SOURCES = ['app']
REPORTER = "min"

task 'compile', 'Compile project', ->
  ep 'coffee --compile app'

task 'watch', 'Watch for changes and compile', ->
  ep 'coffee --watch --compile app'

task "test", "Run tests", ->
  ep "./node_modules/.bin/mocha
   test --recursive
   --compilers coffee:coffee-script 
   --require coffee-script 
   --require test/testHelper.coffee
   --reporter #{REPORTER}
   --colors"