desc "Create a new widget"
task :create_widget, :name do |t, args|
  name = args[:name]
  ['images','scripts','styles'].each do |d|
    `mkdir -p app/#{name}/#{d}`
    `touch app/#{name}/#{d}/.gitkeep`
  end
  `touch app/#{name}/.gitkeep`
  `touch app/#{name}/#{name}.html`
  `mkdir -p app/#{name}/scripts/coffee`
  `mkdir -p app/#{name}/scripts/js`
  `touch app/#{name}/scripts/coffee/.gitkeep`
  `touch app/#{name}/scripts/coffee/#{name}.coffee`
  `touch app/#{name}/scripts/js/.gitkeep` 
  `mkdir -p app/#{name}/styles/css`
  `touch app/#{name}/styles/css/.gitkeep`
  `touch app/#{name}/styles/css/#{name}.css`
end

task :default do
  puts "To create a new widget: `rake create_widget['widget_name']`"
end