// Generated by CoffeeScript 1.6.2
(function() {
  var foo, root;

  foo = function() {
    return "foo";
  };

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.foo = foo;

}).call(this);
